spring.application.name=SecurityDemo

spring.datasource.url=jdbc:mysql://localhost\:3306/Security_Demo
spring.datasource.username=root
spring.datasource.password=Husnain786

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=qqTChGDw85LD10zPnyg4ZQaeK2/K/Yq/ihub7HX7Qmk=
jwt.issuer=SecurityDemo-api
jwt.expiry=900